version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
  backend:
    build:
      context: ./backend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
